### PR TITLE
feature/add-artifactory-repo

### PR DESCRIPTION
**Pull request by YunaBraska**
feature/add-artifactory-repo

### CODE REVIEW

**Comment by MichaelSp** [comment]
would you please consider releasing this? Looks like it is still missing -> https://search.maven.org/search?q=berlin.yuna

**Comment by YunaBraska** [comment]
@MichaelSp as long as the quality of this library is to low, i added it to my repository https://artifactory.yuna.berlin/libs-release/berlin/yuna/system-util/

**Comment by MichaelSp** [comment]
Sure, but I currently have big issues resolving that repo behind our corporate firewall. It's *pita* to use https://github.com/YunaBraska/nats-streaming-server-embedded (which is quite nice by the way)

**Comment by YunaBraska** [comment]
„Pita“? Hm than i will have to upload it to maven central. But it could take a while, i am still experimenting on my build/deploy process, as you need also parent pom after system util…

**Comment by MichaelSp** [comment]
I'm all for quality, so please take your time. I just wanted to raise awareness to this. 
-> [pita](https://www.urbandictionary.com/define.php?term=pita)

**Pull request merged**
